[2024-09-20T13:15:28.378+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T13:15:28.395+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-20T13:12:32.852119+00:00 [queued]>
[2024-09-20T13:15:28.402+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-20T13:12:32.852119+00:00 [queued]>
[2024-09-20T13:15:28.402+0000] {taskinstance.py:2865} INFO - Starting attempt 4 of 4
[2024-09-20T13:15:28.594+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-20 13:12:32.852119+00:00
[2024-09-20T13:15:28.603+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-20T13:15:28.604+0000] {standard_task_runner.py:72} INFO - Started process 174 to run task
[2024-09-20T13:15:28.604+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'load_data', 'manual__2024-09-20T13:12:32.852119+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpqzkvmhlt']
[2024-09-20T13:15:28.607+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask load_data
[2024-09-20T13:15:28.644+0000] {task_command.py:467} INFO - Running <TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-20T13:12:32.852119+00:00 [running]> on host 299ec99d9d69
[2024-09-20T13:15:28.717+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T13:12:32.852119+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-20T13:12:32.852119+00:00'
[2024-09-20T13:15:28.718+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T13:15:28.732+0000] {NYC_Taxi_pipeline.py:43} INFO - Start to load data
[2024-09-20T13:15:28.733+0000] {data_process.py:28} INFO - Loading data into table trip...
[2024-09-20T13:15:30.795+0000] {data_process.py:51} INFO - Data shape after dropna: (339807, 20)
[2024-09-20T13:15:30.895+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-09-20T13:17:02.835+0000] {data_process.py:71} INFO - Data loaded successfully into table trip with 339807 rows
[2024-09-20T13:17:02.840+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-09-20T13:17:02.948+0000] {NYC_Taxi_pipeline.py:46} INFO - Load data done
[2024-09-20T13:17:02.949+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-20T13:17:02.960+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T13:17:02.961+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=load_data, run_id=manual__2024-09-20T13:12:32.852119+00:00, execution_date=20240920T131232, start_date=20240920T131528, end_date=20240920T131702
[2024-09-20T13:17:03.009+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-20T13:17:03.024+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T13:17:03.025+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
