[2024-10-01T06:42:25.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-01T06:42:25.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-01T06:42:25.286+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-10-01T06:42:25.286+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-10-01T06:42:25.300+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_staging_layer.dbt_run_green_trip> on 2024-09-30 00:00:00+00:00
[2024-10-01T06:42:25.308+0000] {standard_task_runner.py:63} INFO - Started process 204 to run task
[2024-10-01T06:42:25.311+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Taxi_trip_pipeline', 'dbt_staging_layer.dbt_run_green_trip', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/taxi_trip.py', '--cfg-path', '/tmp/tmpgsowatvc']
[2024-10-01T06:42:25.313+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask dbt_staging_layer.dbt_run_green_trip
[2024-10-01T06:42:25.362+0000] {task_command.py:426} INFO - Running <TaskInstance: Taxi_trip_pipeline.dbt_staging_layer.dbt_run_green_trip scheduled__2024-09-30T00:00:00+00:00 [running]> on host fcb0f9e87e2b
[2024-10-01T06:42:25.441+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='Taxi_trip_pipeline' AIRFLOW_CTX_TASK_ID='dbt_staging_layer.dbt_run_green_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-10-01T06:42:25.442+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-01T06:42:25.454+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-01T06:42:25.455+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/DBT_Project  --project-dir /opt/***/dbt_trip --models green_trip']
[2024-10-01T06:42:25.467+0000] {subprocess.py:86} INFO - Output:
[2024-10-01T06:42:28.109+0000] {subprocess.py:93} INFO - [0m06:42:28  Running with dbt=1.8.0
[2024-10-01T06:42:28.420+0000] {subprocess.py:93} INFO - [0m06:42:28  Registered adapter: postgres=1.8.0
[2024-10-01T06:42:29.097+0000] {subprocess.py:93} INFO - [0m06:42:29  [[33mWARNING[0m]: Deprecated functionality
[2024-10-01T06:42:29.097+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-10-01T06:42:29.097+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-10-01T06:42:29.097+0000] {subprocess.py:93} INFO - information.
[2024-10-01T06:42:29.322+0000] {subprocess.py:93} INFO - [0m06:42:29  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-01T06:42:29.323+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2024-10-01T06:42:29.323+0000] {subprocess.py:93} INFO - - models.fact_trip.Dimensions
[2024-10-01T06:42:29.323+0000] {subprocess.py:93} INFO - - models.fact_trip.staging
[2024-10-01T06:42:29.501+0000] {subprocess.py:93} INFO - [0m06:42:29  Found 4 models, 6 data tests, 3 sources, 566 macros
[2024-10-01T06:42:29.503+0000] {subprocess.py:93} INFO - [0m06:42:29
[2024-10-01T06:42:29.633+0000] {subprocess.py:93} INFO - [0m06:42:29  Concurrency: 3 threads (target='dev')
[2024-10-01T06:42:29.633+0000] {subprocess.py:93} INFO - [0m06:42:29
[2024-10-01T06:42:29.646+0000] {subprocess.py:93} INFO - [0m06:42:29  1 of 1 START sql view model analysis.green_trip ................................ [RUN]
[2024-10-01T06:42:29.676+0000] {subprocess.py:93} INFO - [0m06:42:29  1 of 1 ERROR creating sql view model analysis.green_trip ....................... [[31mERROR[0m in 0.03s]
[2024-10-01T06:42:29.688+0000] {subprocess.py:93} INFO - [0m06:42:29
[2024-10-01T06:42:29.689+0000] {subprocess.py:93} INFO - [0m06:42:29  Finished running 1 view model in 0 hours 0 minutes and 0.18 seconds (0.18s).
[2024-10-01T06:42:29.740+0000] {subprocess.py:93} INFO - [0m06:42:29
[2024-10-01T06:42:29.741+0000] {subprocess.py:93} INFO - [0m06:42:29  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-01T06:42:29.742+0000] {subprocess.py:93} INFO - [0m06:42:29
[2024-10-01T06:42:29.742+0000] {subprocess.py:93} INFO - [0m06:42:29    Compilation Error in model green_trip (models/Staging/green_trip.sql)
[2024-10-01T06:42:29.743+0000] {subprocess.py:93} INFO -   'tripdata' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2024-10-01T06:42:29.743+0000] {subprocess.py:93} INFO - [0m06:42:29
[2024-10-01T06:42:29.744+0000] {subprocess.py:93} INFO - [0m06:42:29  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-01T06:42:30.856+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-01T06:42:30.856+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-01T06:42:30.868+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T06:42:30.871+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Taxi_trip_pipeline, task_id=dbt_staging_layer.dbt_run_green_trip, run_id=scheduled__2024-09-30T00:00:00+00:00, execution_date=20240930T000000, start_date=20241001T064225, end_date=20241001T064230
[2024-10-01T06:42:30.885+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task dbt_staging_layer.dbt_run_green_trip (Bash command failed. The command returned a non-zero exit code 1.; 204)
[2024-10-01T06:42:30.899+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-01T06:42:30.917+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T06:42:30.918+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
