[2024-09-17T18:46:50.304+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T18:46:50.505+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-17T18:46:46.752910+00:00 [queued]>
[2024-09-17T18:46:50.515+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-17T18:46:46.752910+00:00 [queued]>
[2024-09-17T18:46:50.516+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-17T18:46:50.526+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-17 18:46:46.752910+00:00
[2024-09-17T18:46:50.535+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-17T18:46:50.536+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2024-09-17T18:46:50.536+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'load_data', 'manual__2024-09-17T18:46:46.752910+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp0z2h2mic']
[2024-09-17T18:46:50.538+0000] {standard_task_runner.py:105} INFO - Job 199: Subtask load_data
[2024-09-17T18:46:50.576+0000] {task_command.py:467} INFO - Running <TaskInstance: NYC_Taxi_pipeline.load_data manual__2024-09-17T18:46:46.752910+00:00 [running]> on host 103d737d0864
[2024-09-17T18:46:50.663+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T18:46:46.752910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T18:46:46.752910+00:00'
[2024-09-17T18:46:50.664+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T18:46:50.676+0000] {NYC_Taxi_pipeline.py:48} INFO - Start to load data
[2024-09-17T18:46:50.676+0000] {data_process.py:45} INFO - Loading data into table trip...
[2024-09-17T18:46:50.681+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-09-17T18:46:50.682+0000] {data_process.py:60} INFO - Data loaded successfully into table trip With 0 Row
[2024-09-17T18:46:50.682+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-09-17T18:46:50.682+0000] {NYC_Taxi_pipeline.py:51} INFO - Load data done
[2024-09-17T18:46:50.683+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-17T18:46:50.691+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T18:46:50.691+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=load_data, run_id=manual__2024-09-17T18:46:46.752910+00:00, execution_date=20240917T184646, start_date=20240917T184650, end_date=20240917T184650
[2024-09-17T18:46:50.710+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T18:46:50.724+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-17T18:46:50.726+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
